// Generated by gencpp from file dwb_msgs/GenerateTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef DWB_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H
#define DWB_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dwb_msgs/Trajectory2D.h>

namespace dwb_msgs
{
template <class ContainerAllocator>
struct GenerateTrajectoryResponse_
{
  typedef GenerateTrajectoryResponse_<ContainerAllocator> Type;

  GenerateTrajectoryResponse_()
    : traj()  {
    }
  GenerateTrajectoryResponse_(const ContainerAllocator& _alloc)
    : traj(_alloc)  {
  (void)_alloc;
    }



   typedef  ::dwb_msgs::Trajectory2D_<ContainerAllocator>  _traj_type;
  _traj_type traj;





  typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateTrajectoryResponse_

typedef ::dwb_msgs::GenerateTrajectoryResponse_<std::allocator<void> > GenerateTrajectoryResponse;

typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse > GenerateTrajectoryResponsePtr;
typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse const> GenerateTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator1> & lhs, const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.traj == rhs.traj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator1> & lhs, const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dwb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfa75653fc81c4830452cf99eb524cb4";
  }

  static const char* value(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfa75653fc81c483ULL;
  static const uint64_t static_value2 = 0x0452cf99eb524cb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dwb_msgs/GenerateTrajectoryResponse";
  }

  static const char* value(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Trajectory2D traj\n"
"\n"
"\n"
"================================================================================\n"
"MSG: dwb_msgs/Trajectory2D\n"
"# For a given velocity command, the poses that the robot will go to in the allotted time.\n"
"\n"
"# Input Velocity\n"
"nav_2d_msgs/Twist2D velocity\n"
"\n"
"# Poses the robot will go to, given our kinematic model\n"
"geometry_msgs/Pose2D[] poses\n"
"\n"
"# Time difference between the current pose and the poses in the trajectory.\n"
"# Parallel array to poses. Length should be the same.\n"
"duration[] time_offsets\n"
"\n"
"================================================================================\n"
"MSG: nav_2d_msgs/Twist2D\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "traj: ";
    s << std::endl;
    Printer< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >::stream(s, indent + "  ", v.traj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DWB_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H
