// Generated by gencpp from file dwb_msgs/ScoreTrajectory.msg
// DO NOT EDIT!


#ifndef DWB_MSGS_MESSAGE_SCORETRAJECTORY_H
#define DWB_MSGS_MESSAGE_SCORETRAJECTORY_H

#include <ros/service_traits.h>


#include <dwb_msgs/ScoreTrajectoryRequest.h>
#include <dwb_msgs/ScoreTrajectoryResponse.h>


namespace dwb_msgs
{

struct ScoreTrajectory
{

typedef ScoreTrajectoryRequest Request;
typedef ScoreTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScoreTrajectory
} // namespace dwb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dwb_msgs::ScoreTrajectory > {
  static const char* value()
  {
    return "032651f7461f3d88a9c62f67d179fc10";
  }

  static const char* value(const ::dwb_msgs::ScoreTrajectory&) { return value(); }
};

template<>
struct DataType< ::dwb_msgs::ScoreTrajectory > {
  static const char* value()
  {
    return "dwb_msgs/ScoreTrajectory";
  }

  static const char* value(const ::dwb_msgs::ScoreTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::dwb_msgs::ScoreTrajectoryRequest> should match
// service_traits::MD5Sum< ::dwb_msgs::ScoreTrajectory >
template<>
struct MD5Sum< ::dwb_msgs::ScoreTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dwb_msgs::ScoreTrajectory >::value();
  }
  static const char* value(const ::dwb_msgs::ScoreTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwb_msgs::ScoreTrajectoryRequest> should match
// service_traits::DataType< ::dwb_msgs::ScoreTrajectory >
template<>
struct DataType< ::dwb_msgs::ScoreTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::dwb_msgs::ScoreTrajectory >::value();
  }
  static const char* value(const ::dwb_msgs::ScoreTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dwb_msgs::ScoreTrajectoryResponse> should match
// service_traits::MD5Sum< ::dwb_msgs::ScoreTrajectory >
template<>
struct MD5Sum< ::dwb_msgs::ScoreTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dwb_msgs::ScoreTrajectory >::value();
  }
  static const char* value(const ::dwb_msgs::ScoreTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dwb_msgs::ScoreTrajectoryResponse> should match
// service_traits::DataType< ::dwb_msgs::ScoreTrajectory >
template<>
struct DataType< ::dwb_msgs::ScoreTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::dwb_msgs::ScoreTrajectory >::value();
  }
  static const char* value(const ::dwb_msgs::ScoreTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DWB_MSGS_MESSAGE_SCORETRAJECTORY_H
