// Auto-generated. Do not edit!

// (in-package locomotor_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let NavigationState = require('./NavigationState.js');

//-----------------------------------------------------------

class NavigateToPoseFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.state = null;
      this.percent_complete = null;
      this.distance_traveled = null;
      this.estimated_distance_remaining = null;
    }
    else {
      if (initObj.hasOwnProperty('state')) {
        this.state = initObj.state
      }
      else {
        this.state = new NavigationState();
      }
      if (initObj.hasOwnProperty('percent_complete')) {
        this.percent_complete = initObj.percent_complete
      }
      else {
        this.percent_complete = 0.0;
      }
      if (initObj.hasOwnProperty('distance_traveled')) {
        this.distance_traveled = initObj.distance_traveled
      }
      else {
        this.distance_traveled = 0.0;
      }
      if (initObj.hasOwnProperty('estimated_distance_remaining')) {
        this.estimated_distance_remaining = initObj.estimated_distance_remaining
      }
      else {
        this.estimated_distance_remaining = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateToPoseFeedback
    // Serialize message field [state]
    bufferOffset = NavigationState.serialize(obj.state, buffer, bufferOffset);
    // Serialize message field [percent_complete]
    bufferOffset = _serializer.float32(obj.percent_complete, buffer, bufferOffset);
    // Serialize message field [distance_traveled]
    bufferOffset = _serializer.float32(obj.distance_traveled, buffer, bufferOffset);
    // Serialize message field [estimated_distance_remaining]
    bufferOffset = _serializer.float32(obj.estimated_distance_remaining, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateToPoseFeedback
    let len;
    let data = new NavigateToPoseFeedback(null);
    // Deserialize message field [state]
    data.state = NavigationState.deserialize(buffer, bufferOffset);
    // Deserialize message field [percent_complete]
    data.percent_complete = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [distance_traveled]
    data.distance_traveled = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [estimated_distance_remaining]
    data.estimated_distance_remaining = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += NavigationState.getMessageSize(object.state);
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'locomotor_msgs/NavigateToPoseFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '731b38cf0756acb428661980c367590e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    NavigationState state
    float32 percent_complete
    float32 distance_traveled
    float32 estimated_distance_remaining
    
    
    ================================================================================
    MSG: locomotor_msgs/NavigationState
    nav_2d_msgs/Pose2DStamped global_pose
    nav_2d_msgs/Pose2DStamped local_pose
    nav_2d_msgs/Pose2DStamped goal
    nav_2d_msgs/Twist2DStamped current_velocity
    nav_2d_msgs/Twist2DStamped command_velocity
    nav_2d_msgs/Path2D global_plan
    
    ================================================================================
    MSG: nav_2d_msgs/Pose2DStamped
    Header header
    geometry_msgs/Pose2D pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose2D
    # Deprecated
    # Please use the full 3D pose.
    
    # In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.
    
    # If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.
    
    
    # This expresses a position and orientation on a 2D manifold.
    
    float64 x
    float64 y
    float64 theta
    
    ================================================================================
    MSG: nav_2d_msgs/Twist2DStamped
    std_msgs/Header header
    Twist2D velocity
    
    ================================================================================
    MSG: nav_2d_msgs/Twist2D
    float64 x
    float64 y
    float64 theta
    
    ================================================================================
    MSG: nav_2d_msgs/Path2D
    Header header
    geometry_msgs/Pose2D[] poses
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateToPoseFeedback(null);
    if (msg.state !== undefined) {
      resolved.state = NavigationState.Resolve(msg.state)
    }
    else {
      resolved.state = new NavigationState()
    }

    if (msg.percent_complete !== undefined) {
      resolved.percent_complete = msg.percent_complete;
    }
    else {
      resolved.percent_complete = 0.0
    }

    if (msg.distance_traveled !== undefined) {
      resolved.distance_traveled = msg.distance_traveled;
    }
    else {
      resolved.distance_traveled = 0.0
    }

    if (msg.estimated_distance_remaining !== undefined) {
      resolved.estimated_distance_remaining = msg.estimated_distance_remaining;
    }
    else {
      resolved.estimated_distance_remaining = 0.0
    }

    return resolved;
    }
};

module.exports = NavigateToPoseFeedback;
