hseq:
  root: "/local/hpatches-sequences-release"
  seq: ["v", "i"]
  kpt_n: 2048
  start_idx: 0
  suffix:
  overwrite: false
  upright: false
eval:
  loc_model: 'pretrained/contextdesc++/model.ckpt-400000'
  reg_model: 'pretrained/retrieval_model/model.ckpt-550000'
  err_thld: 2.5
reg_feat:
  max_dim: 1024
network:
  dense_desc: false
  reg_feat_dim: 2048
  aug: true
