// Generated by gencpp from file locomotor_msgs/NavigateToPoseAction.msg
// DO NOT EDIT!


#ifndef LOCOMOTOR_MSGS_MESSAGE_NAVIGATETOPOSEACTION_H
#define LOCOMOTOR_MSGS_MESSAGE_NAVIGATETOPOSEACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <locomotor_msgs/NavigateToPoseActionGoal.h>
#include <locomotor_msgs/NavigateToPoseActionResult.h>
#include <locomotor_msgs/NavigateToPoseActionFeedback.h>

namespace locomotor_msgs
{
template <class ContainerAllocator>
struct NavigateToPoseAction_
{
  typedef NavigateToPoseAction_<ContainerAllocator> Type;

  NavigateToPoseAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  NavigateToPoseAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::locomotor_msgs::NavigateToPoseActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::locomotor_msgs::NavigateToPoseActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::locomotor_msgs::NavigateToPoseActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateToPoseAction_

typedef ::locomotor_msgs::NavigateToPoseAction_<std::allocator<void> > NavigateToPoseAction;

typedef boost::shared_ptr< ::locomotor_msgs::NavigateToPoseAction > NavigateToPoseActionPtr;
typedef boost::shared_ptr< ::locomotor_msgs::NavigateToPoseAction const> NavigateToPoseActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator1> & lhs, const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator1> & lhs, const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace locomotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dbc24d4a22f5002a78b774d243eb6b6";
  }

  static const char* value(const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dbc24d4a22f5002ULL;
  static const uint64_t static_value2 = 0xa78b774d243eb6b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "locomotor_msgs/NavigateToPoseAction";
  }

  static const char* value(const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"NavigateToPoseActionGoal action_goal\n"
"NavigateToPoseActionResult action_result\n"
"NavigateToPoseActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/NavigateToPoseActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"NavigateToPoseGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/NavigateToPoseGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"nav_2d_msgs/Pose2DStamped goal\n"
"\n"
"================================================================================\n"
"MSG: nav_2d_msgs/Pose2DStamped\n"
"Header header\n"
"geometry_msgs/Pose2D pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/NavigateToPoseActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"NavigateToPoseResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/NavigateToPoseResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"ResultCode result_code\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/ResultCode\n"
"# This message contains three separate pieces.\n"
"#    A) A code indicating which component(s) the error originates from (bitmask style)\n"
"#    B) A code corresponding with the result_code defined in nav_core2/s.h\n"
"#    C) A freeform string message\n"
"\n"
"# The enumerations below are not necessarily the exclusive values for the codes.\n"
"# Others may implement additional values beyond the ones shown, using custom state machines.\n"
"\n"
"########### Component Values ###############################################\n"
"int32 GLOBAL_COSTMAP = 1\n"
"int32  LOCAL_COSTMAP = 2\n"
"int32 GLOBAL_PLANNER = 4\n"
"int32  LOCAL_PLANNER = 8\n"
"\n"
"########### Result Codes ###################################################\n"
"int32 GENERIC_COSTMAP=0\n"
"int32 COSTMAP_SAFETY=1\n"
"int32 COSTMAP_DATA_LAG=2\n"
"int32 GENERIC_PLANNER=3\n"
"int32 GENERIC_GLOBAL_PLANNER=4\n"
"int32 INVALID_START=5\n"
"int32 START_BOUNDS=6\n"
"int32 OCCUPIED_START=7\n"
"int32 INVALID_GOAL=8\n"
"int32 GOAL_BOUNDS=9\n"
"int32 OCCUPIED_GOAL=10\n"
"int32 NO_GLOBAL_PATH=11\n"
"int32 GLOBAL_PLANNER_TIMEOUT=12\n"
"int32 GENERIC_LOCAL_PLANNER=13\n"
"int32 ILLEGAL_TRAJECTORY=14\n"
"int32 NO_LEGAL_TRAJECTORIES=15\n"
"int32 PLANNER_TF=16\n"
"\n"
"########### Actual Data ####################################################\n"
"int32 component\n"
"int32 result_code\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/NavigateToPoseActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"NavigateToPoseFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/NavigateToPoseFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"NavigationState state\n"
"float32 percent_complete\n"
"float32 distance_traveled\n"
"float32 estimated_distance_remaining\n"
"\n"
"\n"
"================================================================================\n"
"MSG: locomotor_msgs/NavigationState\n"
"nav_2d_msgs/Pose2DStamped global_pose\n"
"nav_2d_msgs/Pose2DStamped local_pose\n"
"nav_2d_msgs/Pose2DStamped goal\n"
"nav_2d_msgs/Twist2DStamped current_velocity\n"
"nav_2d_msgs/Twist2DStamped command_velocity\n"
"nav_2d_msgs/Path2D global_plan\n"
"\n"
"================================================================================\n"
"MSG: nav_2d_msgs/Twist2DStamped\n"
"std_msgs/Header header\n"
"Twist2D velocity\n"
"\n"
"================================================================================\n"
"MSG: nav_2d_msgs/Twist2D\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: nav_2d_msgs/Path2D\n"
"Header header\n"
"geometry_msgs/Pose2D[] poses\n"
;
  }

  static const char* value(const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateToPoseAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::locomotor_msgs::NavigateToPoseAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::locomotor_msgs::NavigateToPoseActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::locomotor_msgs::NavigateToPoseActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::locomotor_msgs::NavigateToPoseActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCOMOTOR_MSGS_MESSAGE_NAVIGATETOPOSEACTION_H
