(cl:defpackage locomotor_msgs-msg
  (:use )
  (:export
   "<NAVIGATETOPOSEACTION>"
   "NAVIGATETOPOSEACTION"
   "<NAVIGATETOPOSEACTIONFEEDBACK>"
   "NAVIGATETOPOSEACTIONFEEDBACK"
   "<NAVIGATETOPOSEACTIONGOAL>"
   "NAVIGATETOPOSEACTIONGOAL"
   "<NAVIGATETOPOSEACTIONRESULT>"
   "NAVIGATETOPOSEACTIONRESULT"
   "<NAVIGATETOPOSEFEEDBACK>"
   "NAVIGATETOPOSEFEEDBACK"
   "<NAVIGATETOPOSEGOAL>"
   "NAVIGATETOPOSEGOAL"
   "<NAVIGATETOPOSERESULT>"
   "NAVIGATETOPOSERESULT"
   "<NAVIGATIONSTATE>"
   "NAVIGATIONSTATE"
   "<RESULTCODE>"
   "RESULTCODE"
  ))

