; Auto-generated. Do not edit!


(cl:in-package locomotor_msgs-msg)


;//! \htmlinclude NavigateToPoseResult.msg.html

(cl:defclass <NavigateToPoseResult> (roslisp-msg-protocol:ros-message)
  ((result_code
    :reader result_code
    :initarg :result_code
    :type locomotor_msgs-msg:ResultCode
    :initform (cl:make-instance 'locomotor_msgs-msg:ResultCode)))
)

(cl:defclass NavigateToPoseResult (<NavigateToPoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateToPoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateToPoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name locomotor_msgs-msg:<NavigateToPoseResult> is deprecated: use locomotor_msgs-msg:NavigateToPoseResult instead.")))

(cl:ensure-generic-function 'result_code-val :lambda-list '(m))
(cl:defmethod result_code-val ((m <NavigateToPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader locomotor_msgs-msg:result_code-val is deprecated.  Use locomotor_msgs-msg:result_code instead.")
  (result_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateToPoseResult>) ostream)
  "Serializes a message object of type '<NavigateToPoseResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'result_code) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateToPoseResult>) istream)
  "Deserializes a message object of type '<NavigateToPoseResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'result_code) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateToPoseResult>)))
  "Returns string type for a message object of type '<NavigateToPoseResult>"
  "locomotor_msgs/NavigateToPoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateToPoseResult)))
  "Returns string type for a message object of type 'NavigateToPoseResult"
  "locomotor_msgs/NavigateToPoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateToPoseResult>)))
  "Returns md5sum for a message object of type '<NavigateToPoseResult>"
  "c880febea4d3566bbda2f661c4a761c2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateToPoseResult)))
  "Returns md5sum for a message object of type 'NavigateToPoseResult"
  "c880febea4d3566bbda2f661c4a761c2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateToPoseResult>)))
  "Returns full string definition for message of type '<NavigateToPoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%ResultCode result_code~%~%================================================================================~%MSG: locomotor_msgs/ResultCode~%# This message contains three separate pieces.~%#    A) A code indicating which component(s) the error originates from (bitmask style)~%#    B) A code corresponding with the result_code defined in nav_core2/s.h~%#    C) A freeform string message~%~%# The enumerations below are not necessarily the exclusive values for the codes.~%# Others may implement additional values beyond the ones shown, using custom state machines.~%~%########### Component Values ###############################################~%int32 GLOBAL_COSTMAP = 1~%int32  LOCAL_COSTMAP = 2~%int32 GLOBAL_PLANNER = 4~%int32  LOCAL_PLANNER = 8~%~%########### Result Codes ###################################################~%int32 GENERIC_COSTMAP=0~%int32 COSTMAP_SAFETY=1~%int32 COSTMAP_DATA_LAG=2~%int32 GENERIC_PLANNER=3~%int32 GENERIC_GLOBAL_PLANNER=4~%int32 INVALID_START=5~%int32 START_BOUNDS=6~%int32 OCCUPIED_START=7~%int32 INVALID_GOAL=8~%int32 GOAL_BOUNDS=9~%int32 OCCUPIED_GOAL=10~%int32 NO_GLOBAL_PATH=11~%int32 GLOBAL_PLANNER_TIMEOUT=12~%int32 GENERIC_LOCAL_PLANNER=13~%int32 ILLEGAL_TRAJECTORY=14~%int32 NO_LEGAL_TRAJECTORIES=15~%int32 PLANNER_TF=16~%~%########### Actual Data ####################################################~%int32 component~%int32 result_code~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateToPoseResult)))
  "Returns full string definition for message of type 'NavigateToPoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%ResultCode result_code~%~%================================================================================~%MSG: locomotor_msgs/ResultCode~%# This message contains three separate pieces.~%#    A) A code indicating which component(s) the error originates from (bitmask style)~%#    B) A code corresponding with the result_code defined in nav_core2/s.h~%#    C) A freeform string message~%~%# The enumerations below are not necessarily the exclusive values for the codes.~%# Others may implement additional values beyond the ones shown, using custom state machines.~%~%########### Component Values ###############################################~%int32 GLOBAL_COSTMAP = 1~%int32  LOCAL_COSTMAP = 2~%int32 GLOBAL_PLANNER = 4~%int32  LOCAL_PLANNER = 8~%~%########### Result Codes ###################################################~%int32 GENERIC_COSTMAP=0~%int32 COSTMAP_SAFETY=1~%int32 COSTMAP_DATA_LAG=2~%int32 GENERIC_PLANNER=3~%int32 GENERIC_GLOBAL_PLANNER=4~%int32 INVALID_START=5~%int32 START_BOUNDS=6~%int32 OCCUPIED_START=7~%int32 INVALID_GOAL=8~%int32 GOAL_BOUNDS=9~%int32 OCCUPIED_GOAL=10~%int32 NO_GLOBAL_PATH=11~%int32 GLOBAL_PLANNER_TIMEOUT=12~%int32 GENERIC_LOCAL_PLANNER=13~%int32 ILLEGAL_TRAJECTORY=14~%int32 NO_LEGAL_TRAJECTORIES=15~%int32 PLANNER_TF=16~%~%########### Actual Data ####################################################~%int32 component~%int32 result_code~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateToPoseResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'result_code))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateToPoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateToPoseResult
    (cl:cons ':result_code (result_code msg))
))
